dataset:
  test_idx: 2
  valid_partial_ratio: 1.0
path: "OUTPUT_FOLDER_PATH" # eg. "2000-01-01/01-01-01"
mode: "best" # best or last
num_workers: 4
pin_memory: True
model:
  backbone: 
  max_length: 
train:
  batch_size: 256