train:
  epochs: 100
  lr: 5e-3
  clip_lr: 5e-8
  batch_size : 256
  gradient_accumulation_steps: 1
  warmup_ratio: 0.05
  weight_decay: 0.1
  log_every_step: 25
  eval_every_epoch: 1

dataset:
  train_idx: [2]
  valid_idx: [2]
  test_idx: [2]
  cls_ratio: 1.0
  train_partial_ratio: 1.0
  valid_partial_ratio: 1.0

model:
  n_mode: 4
  d_model: 512
  clip_loss_ratio: 1.0
  common_semantic_loss_ratio: 0.1
  disc_loss_ratio: 0.1
  rec_loss_ratio: 0.02
  ortho_loss_ratio: 0.0
  temperature: 2.6592
  backbone: openai/clip-vit-base-patch32
  max_length: 30

num_workers: 4
pin_memory: True
use_mixed_precision: True